name: windows-build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: gcc make mingw-w64-x86_64-qt5
    - run: gcc -v
    - run: qmake -v
    - run: qmake
    - run: make -j4
